name: CloudNative PG Cluster Deployment onto Self Hosted K3d Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - certificates/**
      - namespace/**
      - secrets/**
      - cluster/**
      - .github/workflows/tofu-deploy.yml
  pull_request:
    paths:
      - certificates/**
      - namespace/**
      - secrets/**
      - cluster/**
      - .github/workflows/tofu-deploy.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  namespace_deploy:
    name: CloudNative PG Namespace Deployment onto Self Hosted K3d Cluster
    uses: necronizers-cloud/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: CloudNative PG Namespace
      folder_path: namespace
      runners: cloud
    secrets: inherit
      

  certificates_deploy:
    needs: [namespace_deploy]
    name: CloudNative PG Certificates Deployment onto Self Hosted K3d Cluster
    uses: necronizers-cloud/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: CloudNative PG Certificates
      folder_path: certificates
      runners: cloud
    secrets: inherit
      

  secrets_deploy:
    needs: [certificates_deploy]
    name: CloudNative PG Secrets Deployment onto Self Hosted K3d Cluster
    uses: necronizers-cloud/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: CloudNative PG Secrets
      folder_path: secrets
      runners: cloud
    secrets: inherit
      

  cluster_deploy:
    needs: [secrets_deploy]
    name: CloudNative PG Cluster Deployment onto Self Hosted K3d Cluster
    uses: necronizers-cloud/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: CloudNative PG Cluster
      folder_path: cluster
      runners: cloud
    secrets: inherit
      

  ssl_certs_deploy:
    needs: [cluster_deploy]
    name: CloudNative PG SSL Certificates Deployment onto Self Hosted K3d Cluster
    uses: necronizers-cloud/automations/.github/workflows/execute-script.yml@main
    with:
      deployment_name: SSL Certificates
      shell_script: |

        # Sleep till cluster is ready for generating SSL certificates
        echo "Sleeping till cluster is ready for generating SSL certificates..."
        sleep 180

        # Execute script for generating SSL certificates
        chmod +x .github/scripts/ssl-certificates.sh
        bash .github/scripts/ssl-certificates.sh
      runners: cloud
    secrets: inherit
      

